name: Lint
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Run linting
        uses: golangci/golangci-lint-action@v2
        with:
          only-new-issues: true  # Only show new issues for pull requests.
