name: Test
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      -
        name: Run tests
        run: make test
