name: Lint
on:
  push:
    branches-ignore:
      - master
    tags-ignore:
      - v*
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
  lint:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - 
        name: Run linting
        uses: golangci/golangci-lint-action@v2
        with:
          only-new-issues: true  # Only show new issues for pull requests.
  format:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      - 
        name: Run formatting
        run: gofmt -s -w duplocloud duplosdk
      - 
        name: Check if formatting changed
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - 
        name: Commit formatting changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Duplo Githug Bot'
          git config --global user.email 'joe+github-bot@duplocloud.net'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "lint: go fmt"
          git push
