name: Test
on:
  pull_request:
  push:
    branches-ignore:
      - master
      - release/*
    tags-ignore:
      - v*
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.20.0'
      -
        name: Run tests
        run: make test
        env:
          duplo_host: http://localhost:60020
          duplo_token: FAKE

